import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#FFFEFA' },
  content: {
    padding: 26,
    paddingBottom: 30,
    width: '100%',
    maxWidth: 600,
    alignSelf: 'center',
  },
  intro: { marginTop: 0, marginBottom: 14 },
  eyebrow: {
    color: '#7C8B71',
    fontSize: 10,
    letterSpacing: 1.6,
    marginBottom: 14,
  },
  heading: {
    fontSize: 28,
    lineHeight: 41,
    fontWeight: '500',
    color: '#284D40',
    letterSpacing: -1.3,
  },
  description: { fontSize: 12, lineHeight: 21, color: '#7B8474', marginTop: 9 },
  featured: {
    backgroundColor: '#E8EDDF',
    borderRadius: 14,
    paddingHorizontal: 18,
    paddingTop: 12,
    paddingBottom: 8,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  featureLabel: { color: '#5F7655', fontSize: 11, letterSpacing: 1 },
  flower: { fontSize: 20, color: '#8A9C78' },
  quoteMark: {
    fontSize: 42,
    color: '#607C54',
    height: 32,
    marginTop: 2,
    fontFamily: 'Georgia',
  },
  featureQuote: {
    fontSize: 19,
    lineHeight: 30,
    color: '#284D40',
    letterSpacing: -0.6,
  },
  featureAuthor: { fontSize: 11, color: '#74816A', marginTop: 10 },
  featureFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: '#D4DDCA',
    marginTop: 10,
    paddingTop: 0,
    gap: 8,
  },
  featureCaption: { fontSize: 10, color: '#74816A', flex: 1 },
  iconButton: {
    minWidth: 44,
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  section: { marginTop: 0 },
  afterFeatured: { marginTop: 22 },
  sectionTitle: {
    color: '#284D40',
    fontSize: 17,
    fontWeight: '600',
    letterSpacing: -0.6,
  },
  chips: { gap: 9, paddingVertical: 17 },
  chip: {
    paddingHorizontal: 19,
    paddingVertical: 8,
    backgroundColor: '#F2F2E9',
    borderRadius: 25,
  },
  chipText: { fontSize: 12, color: '#65765B' },
  activeChip: { backgroundColor: '#284D40' },
  activeChipText: { color: '#FFFEFA' },
  textButton: { minHeight: 44, justifyContent: 'center' },
  link: { fontSize: 11, color: '#7A8970' },
  empty: {
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 30,
    borderRadius: 12,
    backgroundColor: '#F6F6F0',
    marginTop: 12,
  },
  emptyTitle: { color: '#52684B', fontSize: 14, marginTop: 13 },
  emptyDescription: {
    color: '#818A78',
    fontSize: 12,
    lineHeight: 21,
    textAlign: 'center',
    marginTop: 8,
  },
  smallButton: {
    paddingHorizontal: 20,
    paddingVertical: 14,
    backgroundColor: '#284D40',
    borderRadius: 8,
    marginTop: 20,
  },
  smallButtonText: { color: '#FFFEFA', fontSize: 12 },
  card: {
    paddingHorizontal: 16,
    paddingTop: 4,
    paddingBottom: 14,
    borderWidth: 1,
    borderColor: '#E6E8DD',
    borderRadius: 12,
    marginTop: 12,
    backgroundColor: '#FFFFFC',
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginRight: -10,
  },
  cardMeta: {
    flex: 1,
    color: '#52684B',
    fontSize: 12,
    fontWeight: '500',
    lineHeight: 19,
  },
  cardDivider: { color: '#B4BBAA', fontWeight: '400' },
  tag: { color: '#829274', fontSize: 11, fontWeight: '400' },
  cardQuote: { color: '#344F40', fontSize: 15, lineHeight: 24 },
  endnote: {
    textAlign: 'center',
    color: '#9AA38D',
    fontSize: 10,
    letterSpacing: 1.2,
    marginTop: 34,
  },
  search: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F2F3EB',
    borderRadius: 10,
    paddingLeft: 15,
    marginTop: 23,
  },
  searchInput: {
    flex: 1,
    minWidth: 0,
    padding: 14,
    color: '#284D40',
    fontSize: 13,
  },
  resultCount: {
    fontSize: 11,
    color: '#839076',
    marginTop: 20,
    marginBottom: 4,
  },
  storageNote: { color: '#8B927E', fontSize: 11, marginTop: 15 },
});
